"""create new table SearchHistory

Revision ID: d854f725fe7b
Revises: 88f06418b565
Create Date: 2025-09-28 10:21:25.385823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd854f725fe7b'
down_revision: Union[str, Sequence[str], None] = '88f06418b565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('L', sa.String(), nullable=True),
    sa.Column('b', sa.String(), nullable=True),
    sa.Column('h', sa.String(), nullable=True),
    sa.Column('q_s', sa.String(), nullable=True),
    sa.Column('g_k', sa.String(), nullable=True),
    sa.Column('g_u', sa.String(), nullable=True),
    sa.Column('q_w', sa.String(), nullable=True),
    sa.Column('q_dop', sa.String(), nullable=True),
    sa.Column('E', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    # ### end Alembic commands ###
